pins.digitalWritePin(DigitalPin.P0, 0)
pins.digitalWritePin(DigitalPin.P1, 0)
pins.servoWritePin(AnalogPin.P2, 0)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    pins.servoWritePin(AnalogPin.P2, 90)
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P0, 0)
    for (let index = 0; index < 4; index++) {
        pins.digitalWritePin(DigitalPin.P0, 1)
        basic.pause(1000)
        pins.digitalWritePin(DigitalPin.P0, 0)
    }
    basic.showNumber(5)
    basic.showNumber(4)
    basic.showNumber(3)
    basic.showNumber(2)
    basic.showNumber(1)
    basic.clearScreen()
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.servoWritePin(AnalogPin.P2, 0)
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.showNumber(5)
    basic.showNumber(4)
    basic.showNumber(3)
    basic.showNumber(2)
    basic.showNumber(1)
    basic.clearScreen()
})
